package frames;

import javax.swing.JOptionPane;
import projecto2.Batalla;
import projecto2.Entrenador;

/**
 *
 * @author Acer
 */
public class principal extends javax.swing.JFrame {

    
    public principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botJugar = new javax.swing.JButton();
        botDex = new javax.swing.JButton();
        botSalir = new javax.swing.JButton();
        fotoDex = new javax.swing.JLabel();
        fotoSalir = new javax.swing.JLabel();
        fotoEmpez = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botJugar.setText("Empezar juego");
        botJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botJugarActionPerformed(evt);
            }
        });
        getContentPane().add(botJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, 30));

        botDex.setText("Pokedex");
        botDex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDexActionPerformed(evt);
            }
        });
        getContentPane().add(botDex, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, 30));

        botSalir.setText("Salir");
        botSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 130, 30));

        fotoDex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pokedexmenu.png"))); // NOI18N
        getContentPane().add(fotoDex, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, 140));

        fotoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/SalirImg.jpg"))); // NOI18N
        getContentPane().add(fotoSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 130, 140));

        fotoEmpez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/empezar.png"))); // NOI18N
        getContentPane().add(fotoEmpez, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 130, 140));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Ahora que conoces más a los Pokemon, haz click en \"Empezar juego\" cuando estés listo  para comenzar. Puedes consultar la Pokedex si quieres tener más información sobre los Pokemon a los que te puedes enfrentar. ¡BUENA SUERTE!");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botSalirActionPerformed

    private void botDexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDexActionPerformed
        pokedex dex=new pokedex();
        dex.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botDexActionPerformed

    private void botJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botJugarActionPerformed
        adelante ultimo=new adelante();
        ultimo.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botJugarActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botDex;
    private javax.swing.JButton botJugar;
    private javax.swing.JButton botSalir;
    private javax.swing.JLabel fotoDex;
    private javax.swing.JLabel fotoEmpez;
    private javax.swing.JLabel fotoSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
