/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;



/**
 *
 * @author Acer
 */
public class profOak2 extends javax.swing.JFrame {

  
    
    
    public profOak2() {
        initComponents();
       
        
        
        
        //String nombreGuardado;
        //nombreGuardado=nombreRecibido.getText();
        //nombreRecibido.setText(nombreGuardado);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        present = new javax.swing.JTextArea();
        fotoOak2 = new javax.swing.JLabel();
        nombreRecibido = new javax.swing.JTextField();
        encantado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("CONTINUAR");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 220, 20));

        present.setBackground(new java.awt.Color(204, 204, 255));
        present.setColumns(20);
        present.setLineWrap(true);
        present.setRows(5);
        present.setText("Ahora te entregaré un Pokemon a nivel 5 que te acompañará a lo largo del juego. Haz click en las fotos para saber más sobre ellos. Recuerda bien sus características cuando tengas que elegir uno más tarde.");
        present.setWrapStyleWord(true);
        present.setFocusable(false);
        getContentPane().add(present, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 410, -1));

        fotoOak2.setBackground(new java.awt.Color(204, 204, 255));
        fotoOak2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Oak2.png"))); // NOI18N
        getContentPane().add(fotoOak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 340, 190));

        nombreRecibido.setBackground(new java.awt.Color(204, 204, 255));
        nombreRecibido.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nombreRecibido.setAutoscrolls(false);
        nombreRecibido.setFocusable(false);
        nombreRecibido.setOpaque(false);
        nombreRecibido.setRequestFocusEnabled(false);
        nombreRecibido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreRecibidoActionPerformed(evt);
            }
        });
        getContentPane().add(nombreRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 250, 30));

        encantado.setBackground(new java.awt.Color(204, 204, 255));
        encantado.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        encantado.setText("Encantado de conocerte, ");
        encantado.setAutoscrolls(false);
        encantado.setFocusable(false);
        encantado.setRequestFocusEnabled(false);
        encantado.setVerifyInputWhenFocusTarget(false);
        encantado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encantadoActionPerformed(evt);
            }
        });
        getContentPane().add(encantado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 400, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreRecibidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreRecibidoActionPerformed
        
    }//GEN-LAST:event_nombreRecibidoActionPerformed

    private void encantadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encantadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encantadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        pokiniciales elecc=new pokiniciales();
        elecc.setVisible(true);        
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profOak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profOak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profOak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profOak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profOak2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField encantado;
    private javax.swing.JLabel fotoOak2;
    private javax.swing.JButton jButton1;
    public static javax.swing.JTextField nombreRecibido;
    private javax.swing.JTextArea present;
    // End of variables declaration//GEN-END:variables
}
